#!/bin/bash

cd ~/PFE-Joueur-Echecs

python3 Scripts/bouton.py > /dev/null & #Bouton
pid1=$!
python3 Interface/app.py > logs/flask 2>&1 & #Flask
pid2=$! 
python3 -m http.server 5500 > logs/server 2>&1 & #Server
pid3=$!
firefox http://127.0.0.1:5500/Interface/ >/dev/null 2>&1 & #Firefox

if [ -z "$1" ]; then
    python3 main.py -s -i
    pid4=$!
elif [ "$1" == "1" ] || [ "$1" == "2" ] || [ "$1" == "3" ] ; then
    python3 main.py -s -i --backup "$1"
    pid4=$!
else
    echo "Usage : Lancez sans argument ou avec 1,2 ou 3 pour avoir un backup]"
    exit 1
fi

# Fonction pour tuer tous les processus à l'arrêt
trap "kill $pid1 $pid2 $pid3 $pid4; exit" SIGINT
echo "Disconnected from Server"
echo "Disconnected from Flask"
echo "Disconnected from Button"
echo "Exit"

# Attendre que les processus se terminent
wait $pid1 $pid2 $pid3 $pid4



