train:
  tune:

    num_epochs : 10000
    lr : 0.00003
    batch_size : 16

    input_channels : 112
    filters : 28
    blocks : 10 
    se_channels : 32
    bias : True
    kernel_size : 3
    stride : 1
    padding : 1
    output_dim : 80
    mapping_dim : 1976
    valout1 : 32
    valout2 : 128
    
    alpha : 2
    beta : 0.5
